directories:
  output: setup
  buildResources: build
appId: com.emr.app
productName: EMR
files:
  - filter:
      - frontend/**
      - backend/**
      - backend/app/dist/main.exe
      - '!frontend/src/**'
      - '!backend/venv/**'
      - '!backend/app/build/**'
      - '!backend/app/emr.db'
      - '!backend/app/**.py'
      - '!backend/app/routes/**.py'
      - '!**/.vscode/*'
      - '!src/*'
      - '!{.eslintignore,.eslintrc.cjs,.prettierignore,.prettierrc.yaml,dev-app-update.yml,CHANGELOG.md,README.md}'
      - '!{.env,.env.*,.npmrc,pnpm-lock.yaml}'
asar: false
win:
  executableName: emr
  icon: frontend/edsols.ico
nsis:
  artifactName: ${name}-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
mac:
  icon: frontend/edsols.ico
  entitlementsInherit: build/entitlements.mac.plist
  extendInfo:
    NSCameraUsageDescription: Application requests access to the device's camera.
    NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
  notarize: false
dmg:
  artifactName: ${name}-${version}.${ext}
linux:
  icon: frontend/edsols.ico
  target:
    - AppImage
    - snap
    - deb
  maintainer: electronjs.org
  category: Utility
appImage:
  artifactName: ${name}-${version}.${ext}
npmRebuild: false
publish:
  provider: generic
  url: https://example.com/auto-updates
electronDownload:
  mirror: https://npmmirror.com/mirrors/electron/
electronVersion: 31.4.0
